language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
    
git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy master to gh-pages"
  on:
    branch: master
