language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3

script:
  - yarn build

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  github-token: $GITHUB-TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy master to gh-pages"
  on:
    branch: master
